apiVersion: v2
name: rustcloak-operator
description: |
  The helm-chart for the rustcloak-operator
type: application
icon: https://github.com/DenktMit-eG/rustcloak-operator/raw/refs/heads/main/icon.svg
home: https://rustcloak.withlazers.dev
maintainers:
  - name: Enno Boland
    email: mail@eboland.de
    url: https://github.com/Gottox
version: 0.3.2
appVersion: "v0.3.2"
