apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterkeycloakapiobjects.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories:
    - keycloak
    - all
    kind: ClusterKeycloakApiObject
    plural: clusterkeycloakapiobjects
    shortNames:
    - ckcapi
    singular: clusterkeycloakapiobject
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Instance that API request is sent to
      jsonPath: .spec.endpoint.instanceRef
      name: Instance
      type: string
    - description: true if the realm is ready
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Status String of the resource
      jsonPath: .status.status
      name: Status
      type: string
    - description: time since the realm was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: Custom Resource for Keycloak API requests. The user should not use this resource directly.
        properties:
          spec:
            description: defines an API request to the Keycloak Admin API.
            properties:
              endpoint:
                anyOf:
                - required:
                  - instanceRef
                - required:
                  - clusterInstanceRef
                oneOf:
                - required:
                  - path
                - required:
                  - parent
                properties:
                  clusterInstanceRef:
                    description: The name of the cluster instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  initWorkflow:
                    enum:
                    - GET
                    - POST
                    type: string
                  instanceRef:
                    description: The name of the namespaced instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  parent:
                    anyOf:
                    - required:
                      - parentRef
                    - required:
                      - clusterParentRef
                    properties:
                      clusterParentRef:
                        description: The name of the cluster API Object to which this object belongs to.
                        type: string
                        x-kubernetes-validations:
                        - message: Value is immutable
                          rule: self == oldSelf
                      parentRef:
                        description: The name of the API Object to which this object belongs to.
                        type: string
                        x-kubernetes-validations:
                        - message: Value is immutable
                          rule: self == oldSelf
                      sub_path:
                        type: string
                        x-kubernetes-validations:
                        - message: Value is immutable
                          rule: self == oldSelf
                    required:
                    - sub_path
                    type: object
                  path:
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
              immutablePayload:
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              options:
                nullable: true
                properties:
                  patchFrom:
                    items:
                      oneOf:
                      - required:
                        - secretKeyRef
                      - required:
                        - configMapKeyRef
                      - required:
                        - value
                      properties:
                        configMapKeyRef:
                          description: Selects a key from a ConfigMap.
                          properties:
                            key:
                              description: The key to select.
                              type: string
                            name:
                              description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                            optional:
                              description: Specify whether the ConfigMap or its key must be defined
                              type: boolean
                          required:
                          - key
                          - name
                          type: object
                        path:
                          type: string
                        secretKeyRef:
                          description: SecretKeySelector selects a key of a Secret.
                          properties:
                            key:
                              description: The key of the secret to select from.  Must be a valid secret key.
                              type: string
                            name:
                              description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                            optional:
                              description: Specify whether the Secret or its key must be defined
                              type: boolean
                          required:
                          - key
                          - name
                          type: object
                        value:
                          type: string
                        value_as:
                          default: string
                          enum:
                          - string
                          - number
                          - bool
                          - yaml
                          - json
                          type: string
                      required:
                      - path
                      type: object
                    type: array
                type: object
              payload:
                type: string
            required:
            - endpoint
            - immutablePayload
            - payload
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              instance:
                anyOf:
                - required:
                  - instanceRef
                - required:
                  - clusterInstanceRef
                properties:
                  clusterInstanceRef:
                    description: The name of the cluster instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  instanceRef:
                    description: The name of the namespaced instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: ClusterKeycloakApiObject
        type: object
    served: true
    storage: true
    subresources:
      status: {}
