apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrolemappings.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories:
    - keycloak
    - all
    kind: KeycloakRoleMapping
    plural: keycloakrolemappings
    shortNames:
    - kcrmp
    singular: keycloakrolemapping
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Role Name
      jsonPath: .spec.roleRef
      name: Role Name
      type: string
    - description: Role Ref
      jsonPath: .spec.roleRef
      name: Role Ref
      type: string
    - description: true if the realm is ready
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Status String of the resource
      jsonPath: .status.status
      name: Status
      type: string
    - description: time since the realm was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: represents a mapping between a user or group and a client
        properties:
          spec:
            anyOf:
            - required:
              - roleRef
            - required:
              - keycloakRole
            properties:
              keycloakRole:
                description: The name of the role in keycloak. Mutual exclusive with roleRef
                properties:
                  clientRef:
                    description: The kubernetes resources name of a KeycloakClient object.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  name:
                    description: The name of the role in keycloak
                    type: string
                required:
                - name
                type: object
              roleRef:
                description: The kubernetes resource name of a KeycloakRole object. Mutual exclusive with keycloakRole
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              subject:
                anyOf:
                - required:
                  - userRef
                - required:
                  - groupRef
                description: The object that the role mapping is for
                properties:
                  groupRef:
                    description: The name of a KeycloakGroup resource
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  userRef:
                    description: The name of a KeycloakUser resource
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
            required:
            - subject
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              instance:
                anyOf:
                - required:
                  - instanceRef
                - required:
                  - clusterInstanceRef
                properties:
                  clusterInstanceRef:
                    description: The name of the cluster instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  instanceRef:
                    description: The name of the namespaced instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakRoleMapping
        type: object
    served: true
    storage: true
    subresources:
      status: {}
