apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclientcredentials.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories:
    - keycloak
    - all
    kind: KeycloakClientCredential
    plural: keycloakclientcredentials
    shortNames:
    - kccc
    singular: keycloakclientcredential
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Path to the resource
      jsonPath: .spec.resourcePath
      name: Path
      type: string
    - description: true if the realm is ready
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Status String of the resource
      jsonPath: .status.status
      name: Status
      type: string
    - description: time since the realm was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: represents credentials for a keycloak client
        properties:
          spec:
            anyOf:
            - required:
              - instanceRef
            - required:
              - clusterInstanceRef
            properties:
              clientSecret:
                properties:
                  clientIdKey:
                    nullable: true
                    type: string
                  clientSecretKey:
                    nullable: true
                    type: string
                  secretName:
                    type: string
                required:
                - secretName
                type: object
              clusterInstanceRef:
                description: The name of the cluster instance to which this object belongs to.
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              instanceRef:
                description: The name of the namespaced instance to which this object belongs to.
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              resourcePath:
                type: string
            required:
            - clientSecret
            - resourcePath
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              instance:
                anyOf:
                - required:
                  - instanceRef
                - required:
                  - clusterInstanceRef
                properties:
                  clusterInstanceRef:
                    description: The name of the cluster instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  instanceRef:
                    description: The name of the namespaced instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
              message:
                type: string
              ready:
                type: boolean
              reconcileAttempts:
                format: uint64
                minimum: 0.0
                nullable: true
                type: integer
              resourcePath:
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakClientCredential
        type: object
    served: true
    storage: true
    subresources:
      status: {}
