apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakauthenticationflows.rustcloak.k8s.eboland.de
spec:
  group: rustcloak.k8s.eboland.de
  names:
    categories:
    - keycloak
    - all
    kind: KeycloakAuthenticationFlow
    plural: keycloakauthenticationflows
    shortNames:
    - kcaf
    singular: keycloakauthenticationflow
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: true if the realm is ready
      jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Status String of the resource
      jsonPath: .status.status
      name: Status
      type: string
    - description: time since the realm was created
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: resource to define an Authentication Flow within a [KeycloakRealm](./keycloakrealm.md)
        properties:
          spec:
            anyOf:
            - required:
              - realmRef
            - required:
              - clusterRealmRef
            description: the KeycloakAuthenticationFlow resource
            properties:
              clusterRealmRef:
                description: The name of the cluster realm to which this object belongs to
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
              definition:
                description: |-
                  AuthenticationFlowRepresentation

                  <details><summary>JSON schema</summary>

                  ```json { "type": "object", "properties": { "alias": { "type": "string" }, "authenticationExecutions": { "type": "array", "items": { "$ref": "#/$defs/AuthenticationExecutionExportRepresentation" } }, "builtIn": { "type": "boolean" }, "description": { "type": "string" }, "id": { "type": "string" }, "providerId": { "type": "string" }, "topLevel": { "type": "boolean" } }, "additionalProperties": false } ``` </details>
                properties:
                  alias:
                    nullable: true
                    type: string
                  authenticationExecutions:
                    items:
                      description: |-
                        AuthenticationExecutionExportRepresentation

                        <details><summary>JSON schema</summary>

                        ```json { "type": "object", "properties": { "authenticator": { "type": "string" }, "authenticatorConfig": { "type": "string" }, "authenticatorFlow": { "type": "boolean" }, "autheticatorFlow": { "type": "boolean" }, "flowAlias": { "type": "string" }, "priority": { "type": "integer", "format": "int32", "maximum": 2147483647.0, "minimum": -2147483648.0 }, "requirement": { "type": "string", "enum": [ "ALTERNATIVE", "CONDITIONAL", "DISABLED", "REQUIRED" ] }, "userSetupAllowed": { "type": "boolean" } }, "additionalProperties": false } ``` </details>
                      properties:
                        authenticator:
                          nullable: true
                          type: string
                        authenticatorConfig:
                          nullable: true
                          type: string
                        authenticatorFlow:
                          nullable: true
                          type: boolean
                        autheticatorFlow:
                          nullable: true
                          type: boolean
                        flowAlias:
                          nullable: true
                          type: string
                        priority:
                          format: int32
                          nullable: true
                          type: integer
                        requirement:
                          description: |-
                            AuthenticationExecutionExportRepresentationRequirement

                            <details><summary>JSON schema</summary>

                            ```json { "type": "string", "enum": [ "ALTERNATIVE", "CONDITIONAL", "DISABLED", "REQUIRED" ] } ``` </details>
                          enum:
                          - ALTERNATIVE
                          - CONDITIONAL
                          - DISABLED
                          - REQUIRED
                          nullable: true
                          type: string
                        userSetupAllowed:
                          nullable: true
                          type: boolean
                      type: object
                    type: array
                  builtIn:
                    nullable: true
                    type: boolean
                  description:
                    nullable: true
                    type: string
                  id:
                    nullable: true
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  providerId:
                    nullable: true
                    type: string
                  topLevel:
                    nullable: true
                    type: boolean
                type: object
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: has(self.id) == has(oldSelf.id)
              options:
                description: Options for the request to the Keycloak Admin API.
                nullable: true
                type: object
              patchFrom:
                additionalProperties:
                  description: EnvVarSource represents a source for the value of an EnvVar.
                  properties:
                    configMapKeyRef:
                      description: Selects a key of a ConfigMap.
                      properties:
                        key:
                          description: The key to select.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the ConfigMap or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    fieldRef:
                      description: 'Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[''<KEY>'']`, `metadata.annotations[''<KEY>'']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.'
                      properties:
                        apiVersion:
                          description: Version of the schema the FieldPath is written in terms of, defaults to "v1".
                          type: string
                        fieldPath:
                          description: Path of the field to select in the specified API version.
                          type: string
                      required:
                      - fieldPath
                      type: object
                    resourceFieldRef:
                      description: 'Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.'
                      properties:
                        containerName:
                          description: 'Container name: required for volumes, optional for env vars'
                          type: string
                        divisor:
                          description: Specifies the output format of the exposed resources, defaults to "1"
                          type: string
                        resource:
                          description: 'Required: resource to select'
                          type: string
                      required:
                      - resource
                      type: object
                    secretKeyRef:
                      description: Selects a key of a secret in the pod's namespace
                      properties:
                        key:
                          description: The key of the secret to select from.  Must be a valid secret key.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the Secret or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    valueAs:
                      enum:
                      - auto
                      - string
                      - number
                      - yaml
                      - json
                      - bool
                      nullable: true
                      type: string
                  type: object
                description: Defines additional values that can be loaded from secrets or configmaps. Field selectors are not supported. For more informations see [the patches documentation](../configuration/patches.md).
                type: object
              patchFrom2:
                items:
                  description: EnvVarSource represents a source for the value of an EnvVar.
                  properties:
                    configMapKeyRef:
                      description: Selects a key of a ConfigMap.
                      properties:
                        key:
                          description: The key to select.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the ConfigMap or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    fieldRef:
                      description: 'Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[''<KEY>'']`, `metadata.annotations[''<KEY>'']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.'
                      properties:
                        apiVersion:
                          description: Version of the schema the FieldPath is written in terms of, defaults to "v1".
                          type: string
                        fieldPath:
                          description: Path of the field to select in the specified API version.
                          type: string
                      required:
                      - fieldPath
                      type: object
                    path:
                      type: string
                    resourceFieldRef:
                      description: 'Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.'
                      properties:
                        containerName:
                          description: 'Container name: required for volumes, optional for env vars'
                          type: string
                        divisor:
                          description: Specifies the output format of the exposed resources, defaults to "1"
                          type: string
                        resource:
                          description: 'Required: resource to select'
                          type: string
                      required:
                      - resource
                      type: object
                    secretKeyRef:
                      description: Selects a key of a secret in the pod's namespace
                      properties:
                        key:
                          description: The key of the secret to select from.  Must be a valid secret key.
                          type: string
                        name:
                          description: 'Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        optional:
                          description: Specify whether the Secret or its key must be defined
                          type: boolean
                      required:
                      - key
                      - name
                      type: object
                    valueAs:
                      enum:
                      - auto
                      - string
                      - number
                      - yaml
                      - json
                      - bool
                      nullable: true
                      type: string
                  required:
                  - path
                  type: object
                type: array
              realmRef:
                description: The name of the realm to which this object belongs to
                type: string
                x-kubernetes-validations:
                - message: Value is immutable
                  rule: self == oldSelf
            required:
            - definition
            type: object
          status:
            nullable: true
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
                      format: date-time
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              instance:
                anyOf:
                - required:
                  - instanceRef
                - required:
                  - clusterInstanceRef
                properties:
                  clusterInstanceRef:
                    description: The name of the cluster instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                  instanceRef:
                    description: The name of the namespaced instance to which this object belongs to.
                    type: string
                    x-kubernetes-validations:
                    - message: Value is immutable
                      rule: self == oldSelf
                type: object
              message:
                type: string
              ready:
                type: boolean
              resourcePath:
                type: string
              status:
                type: string
            required:
            - ready
            type: object
        required:
        - spec
        title: KeycloakAuthenticationFlow
        type: object
    served: true
    storage: true
    subresources:
      status: {}
